spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
#        use_sql_comments: true
#    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: m_pT5WYQo6xw4gBMXAhM
            client-secret: Pzo483lfaJ
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
          google:
            client-name: google
            client-id: 978861459277-qjeidlpssgbud6psj6fgmvfm0ibr9jnh.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    org.hibernate.SQL: debug


jwt:
  secret: ${JWT_SECRET_KEY}
